{% set name = "dash-html-components" %}
{% set filename = "dash_html_components" %}
{% set version = "1.1.3" %}
{% set sha256 = "88adb77a674d5d7d0835d71c469f6e7b4aa692f9673808a474d244b71863c58a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - dash  # not listed in the setup.py

test:
  imports:
    - dash_html_components

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash-html-components
  license: MIT
  license_family: MIT
  # TODO : Update this once plotly packages it correctly:
  # https://github.com/plotly/dash-html-components/pull/46
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: Dash UI HTML component suite

extra:
  recipe-maintainers:
    - moorepants
